/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlVehiculoIface;
import controlador.CtrlVehiculoImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import parqueadero.java.Vehiculo;

/**
 *
 * @author Mao
 */
public class VistaVehiculos extends javax.swing.JFrame {

    CtrlVehiculoIface ctrlVehiculo;
    List<Vehiculo> lista = new ArrayList();
    
    /**
     * Creates new form vistaVehiculos
     */
    public VistaVehiculos() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVehiculos = new javax.swing.JTable();
        JBotton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableVehiculos.setToolTipText("");
        jTableVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVehiculos);

        JBotton1.setText("Refrescar");
        JBotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBotton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBotton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        setSize(new java.awt.Dimension(611, 324));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotton1ActionPerformed
        listar();
    }//GEN-LAST:event_JBotton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        crear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVehiculosMouseClicked
        JTable tabla = (JTable)evt.getSource();
        int pos = tabla.getSelectedRow();
        int id = lista.get(pos).getId();
        int val = JOptionPane.showOptionDialog(rootPane, "¿Qué desea hacer?","Acción", JOptionPane.DEFAULT_OPTION, 
                JOptionPane.PLAIN_MESSAGE, null, new String []{"Dar salida","Hora de entrada","Borrar"},null);
        if (val == 0 ){ //Editar
            editar(id);
        } else if(val == 1) {
            ver (id);
            
        }else { //borar
            borrar(id);
        }        
    }//GEN-LAST:event_jTableVehiculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBotton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVehiculos;
    // End of variables declaration//GEN-END:variables

    private void listar() {
        ctrlVehiculo = new CtrlVehiculoImpl();                                  // Inicializar controlador
        lista = ctrlVehiculo.listar();                                          // Consultar lista de registros    
        String[] titulos = new String[]{"Placa","Celda","Ingreso","Salida"};    // Variables de la tabla
        String [][] datos = new String[lista.size()][4];
        
        for (int i = 0; i < lista.size(); i++){                                 // Llenar datos
            Vehiculo obj = lista.get(i);        
            datos[i][0] = obj.getPlaca();
            datos[i][1] = String.valueOf(obj.getParqueaderos_id());
            datos[i][2] = String.valueOf(obj.getIngreso());
            datos[i][3] = String.valueOf(obj.getSalida());
        }
        
        DefaultTableModel modelo = new DefaultTableModel();                     // Arma la tabla
        modelo.setDataVector(datos, titulos);
        jTableVehiculos.setModel(modelo);
    }
    
    private void ver (int id){
        ctrlVehiculo = new CtrlVehiculoImpl();
        Vehiculo vehiculo = ctrlVehiculo.ver(id);
    }
        
    private void crear (){
        VistaVehiculoCrear vistaCrear = new VistaVehiculoCrear();
        vistaCrear.setVisible(true);
    }

    private void editar (int id){
        ctrlVehiculo = new CtrlVehiculoImpl();
        Vehiculo vehiculo = ctrlVehiculo.editar(id);
        ctrlVehiculo.modificar(vehiculo);
    }

    private void borrar (int id){
        ctrlVehiculo = new CtrlVehiculoImpl();
        ctrlVehiculo.borrar(id);
    }
}
